name: mynotes
description: Learning Fluttter/Dart | App based on YT tutorial 'Free Flutter Course'
publish_to: 'none'
version: 1.0.0+1flu

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.12.1
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.6
  firebase_analytics: ^10.6.2
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  get: ^4.6.6
  # logger: ^2.0.2+1
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.3

flutter:
  uses-material-design: true
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: fonts/TitilliumWeb-Black.ttf
          weight: 900
        - asset: fonts/TitilliumWeb-Bold.ttf
          weight: 700
        - asset: fonts/TitilliumWeb-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/TitilliumWeb-ExtraLight.ttf
          weight: 200
        - asset: fonts/TitilliumWeb-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/TitilliumWeb-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/TitilliumWeb-Light.ttf
          weight: 200
        - asset: fonts/TitilliumWeb-LightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/TitilliumWeb-Regular.ttf
          weight: 400
  assets:
    - assets/icon/icon.png
    - assets/splash/branding_dark.png
    - assets/splash/branding.png
    - assets/splash/splash-invert.png
    - assets/splash/splash.png
    - assets/screenshots.jpg
