name: mynotes
description: Learning Fluttter/Dart | App based on YT tutorial 'Free Flutter Course'
publish_to: 'none'
version: 1.0.0+1flu

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.12.1
  cupertino_icons: ^1.0.6
  firebase_analytics: ^10.6.2
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  logger: ^2.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon.png
    - assets/icon/logo.png
    - assets/icon/logo_big.png
